#Colores modo claro 
C_BARRA_SUPERIOR_CLARO = "B0BBC6"
C_BOTON_MENU_CLARO = "#7595B8"
C_BOTON_AREATRABAJO_CLARO = "DodgerBlue2"

#Colore modo oscurio
C_BARRA_SUPERIOR_OSCURO = "#2A3138"
C_BOTON_MENU_OSCURO = "#32404F"
C_BOTON_AREATRABAJO_OSCURO = "DodgerBlue2"

#Colores Oscuros
COLOR_DE_FONDO_DARK = "#1e2435"
COLOR_DE_TEXTO_DARK = "white"
COLOR_BOTONES_ESPECIALES_DARK = "#52c9dc"
COLOR_BOTONES_DARK = "#1e2435"
COLOR_CAJA_TEXTO_DARK = "#1a1b28"

#Colores Claros
COLOR_DE_FONDO_LIGHT = "#ffffff"
COLOR_DE_TEXTO_LIGHT= "black"
COLOR_BOTONES_ESPECIALES_LIGHT = "#52c9dc"
COLOR_BOTONES_LIGHT = "#f2f8fc"
COLOR_CAJA_TEXTO_LIGHT = "#ffffff"